application.id=order-processor
client.id=order-processor

bootstrap.servers=${BOOTSTRAP_SERVERS:-localhost:9092}
schema.registry.url=${SCHEMA_REGISTRY_URL:-http://localhost:8081}
auto.register.schemas=true

default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
default.value.serde=io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde

group.protocol=streams
ensure.explicit.internal.resource.naming=true

default.deserialization.exception.handler=org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
compression.type=lz4
metrics.recording.level=INFO

num.stream.threads=1
commit.interval.ms=30000
