org.slf4j.simpleLogger.log.org.apache.kafka.common.config=WARN
org.slf4j.simpleLogger.log.org.apache.kafka.clients=WARN
org.slf4j.simpleLogger.log.io.confluent.kafka.serializers=WARN

org.slf4j.simpleLogger.log.com.example=INFO

org.slf4j.simpleLogger.log.org.apache.kafka.streams=INFO

org.slf4j.simpleLogger.defaultLogLevel=WARN
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS
org.slf4j.simpleLogger.showShortLogName=true
